ALTER TABLE [dbo].[FileSystem]
    ADD CONSTRAINT [IX_FileSystemUniqueNameAndParentId] UNIQUE NONCLUSTERED ([Name] ASC, [ParentId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

