ALTER TABLE [dbo].[DirPath]
    ADD CONSTRAINT [PK_Directory_1] PRIMARY KEY CLUSTERED ([Id] ASC, [FullName] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

